// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Mobiskribe.Views
{
	public partial class IntroductionViewController : UIViewController
	{
		public IntroductionViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
