// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Mobiskribe.Views
{
	public partial class LoginViewNavigator : UINavigationController
	{
		public LoginViewNavigator (IntPtr handle) : base (handle)
		{
		}
	}
}
